"""User-registered SSH target for the sandboxed IDE terminal - opt-in,
one host per user. We never store the user's server credentials: this
table only holds host/port/label + a public-key fingerprint for display.
The actual keypair is generated by RG_Terminal_Sandbox inside the user's
own persistent container (see that service's docker_manager.py); the
private half never reaches this service or its database.
"""
from __future__ import annotations

from pydantic import BaseModel, Field
from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from .config import settings
from .db import get_db
from .deps import _get_identity_from_request, _utcnow
from .models import UserSshHost

router = APIRouter()


class UserSshHostCreate(BaseModel):
    host: str = Field(..., min_length=1, max_length=255)
    port: int = Field(default=22, ge=1, le=65535)
    label: str | None = None


def _to_response(row: UserSshHost) -> dict:
    return {
        "host": row.host,
        "port": row.port,
        "label": row.label,
        "public_key_fingerprint": row.public_key_fingerprint,
        "created_at": row.created_at.isoformat() if row.created_at else None,
    }


@router.get("/auth/user/ssh-hosts")
async def get_user_ssh_host(request: Request, db: AsyncSession = Depends(get_db)):
    """The current user's single registered SSH target, if any."""
    identity = await _get_identity_from_request(request, db)
    result = await db.execute(select(UserSshHost).where(UserSshHost.user_id == identity.user_id))
    row = result.scalar_one_or_none()
    return {"registered": row is not None, "host_entry": _to_response(row) if row else None}


@router.post("/auth/user/ssh-hosts")
async def upsert_user_ssh_host(
    request: Request,
    payload: UserSshHostCreate,
    db: AsyncSession = Depends(get_db),
):
    """Register (or replace) the user's one allowed SSH target. Deliberately
    a single row per user (unique index on user_id) - this is meant to stay
    a narrow, opt-in exception, not a general egress allowlist.
    """
    identity = await _get_identity_from_request(request, db)

    result = await db.execute(select(UserSshHost).where(UserSshHost.user_id == identity.user_id))
    row = result.scalar_one_or_none()
    if row:
        row.host = payload.host
        row.port = payload.port
        row.label = payload.label
        # Registering a new host invalidates any previously shown fingerprint
        # until RG_Terminal_Sandbox (re)confirms a keypair for this target.
        row.public_key_fingerprint = None
    else:
        row = UserSshHost(
            user_id=identity.user_id,
            host=payload.host,
            port=payload.port,
            label=payload.label,
        )
        db.add(row)

    await db.commit()
    await db.refresh(row)
    return _to_response(row)


@router.delete("/auth/user/ssh-hosts")
async def delete_user_ssh_host(request: Request, db: AsyncSession = Depends(get_db)):
    identity = await _get_identity_from_request(request, db)
    result = await db.execute(select(UserSshHost).where(UserSshHost.user_id == identity.user_id))
    row = result.scalar_one_or_none()
    if row:
        await db.delete(row)
        await db.commit()
    return {"deleted": True}


def _require_internal(request: Request) -> None:
    internal_key = request.headers.get("x-internal-service-key")
    client_host = request.client.host if request.client else ""
    forwarded_for = request.headers.get("x-forwarded-for", "")
    is_internal = (
        internal_key == settings.INTERNAL_SERVICE_KEY or
        forwarded_for.startswith("10.") or
        forwarded_for.startswith("172.") or
        client_host in ["127.0.0.1", "localhost"] or
        client_host.startswith("10.") or
        client_host.startswith("172.")
    )
    if not is_internal and settings.ENVIRONMENT != "development":
        raise HTTPException(status_code=403, detail="Internal endpoint - access denied")


@router.get("/auth/internal/user-ssh-hosts/{user_id}")
async def get_user_ssh_host_internal(user_id: str, request: Request, db: AsyncSession = Depends(get_db)):
    """Called by RG_Terminal_Sandbox when creating a terminal container, to
    decide whether this user gets a per-session egress sidecar and what
    host:port it should allow.
    """
    _require_internal(request)
    result = await db.execute(select(UserSshHost).where(UserSshHost.user_id == user_id))
    row = result.scalar_one_or_none()
    if not row:
        return {"registered": False, "host_entry": None}
    return {"registered": True, "host_entry": _to_response(row)}


class SshFingerprintUpdate(BaseModel):
    public_key_fingerprint: str


@router.patch("/auth/internal/user-ssh-hosts/{user_id}/fingerprint")
async def set_user_ssh_host_fingerprint(
    user_id: str,
    payload: SshFingerprintUpdate,
    request: Request,
    db: AsyncSession = Depends(get_db),
):
    """Called by RG_Terminal_Sandbox after it (re)generates the user's
    keypair, so the fingerprint can be shown back to the user for
    verification without ever exposing the private key.
    """
    _require_internal(request)
    result = await db.execute(select(UserSshHost).where(UserSshHost.user_id == user_id))
    row = result.scalar_one_or_none()
    if not row:
        raise HTTPException(status_code=404, detail="No registered host for this user")
    row.public_key_fingerprint = payload.public_key_fingerprint
    await db.commit()
    return {"success": True}
